
server:
  port: 9000

logging:
  level:
    org.hibernate.SQL: trace

com:
  justgifit:
    createResultDir: true
    gifLocation: ${java.io.tmpdir}/gif

spring:
  http:
    multipart:
      maxFileSize: 50MB
      maxRequestSize: 50MB
  mvc:
    view:
      prefix: /templates/
      suffix: .html
    favicon:
      enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/idziak_db
    username: idziak
    password: idziak
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        ddlAuto: create
        formatSql: true
        showSql: true
    databasePlatform: org.hibernate.dialect.MySQL5InnoDBDialect